### ISSUE TITLE
Fail Deploy

### ISSUE THREAD

**Issue by davidmarinangeli** [actions-on-google/dialogflow-facts-about-google-nodejs#13]
I'm trying to deploy this firebase project but there's a problem when i write "firebase deploy" in the shell:

Error: Error occurred while parsing your function triggers.

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _mylocalpath_\npm\node_modules\firebase-tools\lib\triggerParser.js:18:11
    at Object.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:32:3)
    at Module._compile (module.js:409:26)

**Comment by KamalGalrani** [comment]
Same issue! Anyone?

**Comment by KamalGalrani** [comment]
Fixed by upgrading node version to 6.11.2

**Comment by davidmarinangeli** [comment]
@KamalGalrani thanks a lot, solved.
